version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # SSL通信の場合
      #- ./path_to_cert.crt:/etc/nginx/path_to_cert.crt
      #- ./path_to_key.key:/etc/nginx/path_to_key.key
    depends_on:
      - api
  api:
    build: .
    ports:
      - "5000:5000"

